### ISSUE TITLE
SSH Manager Tab is blank

### ISSUE THREAD

**Issue by gingabeard** [JetBrains/teamcity-docker-server#27]
Hi
I'm trying to add an SSH key, but there's no content on the SSH Manager tab. Just blank.
Pls see screenshot:
![image](https://user-images.githubusercontent.com/38758494/49741225-db9eb600-fc8d-11e8-8ad5-4c0adddf191b.png)
I'm using docker-compose on W10:
`image: jetbrains/teamcity-server:latest`
TIA

**Comment by dtretyakov** [comment]
@gingabeard, could you please file an issue in [the TeamCity issue tracker](https://youtrack.jetbrains.com/issues/TW) and privately attach `teamcity-server.log` file shared to `teamcity-developers` user group?

**Comment by visma-henriklarsen** [comment]
We still see this issue in TeamCity 2018.2.4 Windows 2019 Docker container, which prevents us from using TeamCity/Docker. I believe this will be a fairly big issue for many enterprise customers.  

@kir I'm not familiar with the work flow in this repository, but would expect the case to be open until it was fixed, unless this issue is intentional/by design which I certainly hope is not the case..:-)
